#
#   This CI triggered on PRs.
#
#   Verify if `npm run build` pass
#
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm --version
    - run: which npm
    - run: npm config ls -l
    - run: npm install
    - run: npm list npm-run-all
    - run: ls node_modules/.bin/
    - run: npm run build
