#
#   This CI triggered on Dependabot PRs.
#
#   1. Runs `npm test`, which includes lint, type-checking, and unit tests on node.js LTS 10,12,14
#      and the current version (v15)
#
on:
  - pull_request_target

jobs:
  dependabot-test:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      STAGING_USERNAME_1: ${{ secrets.STAGING_USERNAME_1 }}
      STAGING_PASSWORD_1: ${{ secrets.STAGING_PASSWORD_1 }}
      STAGING_USERNAME_2: ${{ secrets.STAGING_USERNAME_2 }}
      STAGING_PASSWORD_2: ${{ secrets.STAGING_PASSWORD_2 }}
      STAGING_USERNAME_3: ${{ secrets.STAGING_USERNAME_3 }}
      STAGING_PASSWORD_3: ${{ secrets.STAGING_PASSWORD_3 }}
      STAGING_SUBSCRIPTION_ID_1: ${{ secrets.STAGING_SUBSCRIPTION_ID_1 }}
      KEYCLOAK_ADDRESS: ${{ secrets.KEYCLOAK_ADDRESS }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      API_ENDPOINT_ADDRESS: ${{ secrets.API_ENDPOINT_ADDRESS }}
      TOKEN_HOST: ${{ secrets.TOKEN_HOST }}
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
