#
#   This CI triggered on PRs.
#
#   1. Runs `npm test`, which includes lint, type-checking, and unit tests on node.js LTS 10,12,14
#      and the current version (v15)
#
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STAGING_USERNAME_1: ${{ secrets.STAGING_USERNAME_1 }}
      STAGING_PASSWORD_1: ${{ secrets.STAGING_PASSWORD_1 }}
      STAGING_USERNAME_2: ${{ secrets.STAGING_USERNAME_2 }}
      STAGING_PASSWORD_2: ${{ secrets.STAGING_PASSWORD_2 }}
      KEYCLOAK_ADDRESS: ${{ secrets.KEYCLOAK_ADDRESS }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      API_ENDPOINT_ADDRESS: ${{ secrets.API_ENDPOINT_ADDRESS }}
      TOKEN_HOST: ${{ secrets.TOKEN_HOST }}
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # there is a problem in node 16 in CI
    # which can't find eslint/eslint from dependencies
    # so we install them global
    - run: npm install -g eslint
    - run: npm install -g jest
    - run: npm install
    - run: npm test
